spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId:
            clientSecret:
            scope: openid, profile, email, https://www.googleapis.com/auth/youtube
